version: "3.8"
services:
  api-service:
    build: ./ApiService
    depends_on:
      - zuul
      - id-gen-service
      - approver-service
  approver-service:
    build: ./ApproverService
    depends_on:
      - zuul
      - mailer-service
  id-gen-service:
    build: ./IdGeneratorService
    depends_on:
      - zuul
  mailer-service:
    build: ./MailerService
    depends_on:
      - zuul
  zuul:
    build: ./ApiZuulGateway
    depends_on:
      - consul
      - rabbitmq
      - api-db
      - dto
  dto:
    build: ./ApiDto
    image: myorg/dto
  api-db:
    image: "postgres:12-alpine"
  consul:
    image: "consul:1.8"
    ports:
      - 8500:8500
  rabbitmq:
    image: "rabbitmq:3.8-alpine"
