version: "3.8"
services:
  api-db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "testdb"
    ports:
      - 5437:5432
  consul:
    image: "consul:1.8"
    ports:
      - 8500:8500
  rabbitmq:
    image: "rabbitmq:3.8-alpine"
    ports:
      - 5672:5672
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - 9411:9411
  logstash:
    build: ./ELK/logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./ApiService/logs/api-ws.log:/api-logs/api-ws.log
      - ./ApproverService/logs/approver-ws.log:/api-logs/approver-ws.log
      - ./IdGneratorService/logs/id-ws.log:/api-logs/id-ws.log
      - ./MailerService/logs/api-ws.log:/api-logs/mailer-ws.log
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.1"
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  kibana:
    image: "kibana:7.8.1"
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
